### ISSUE TITLE
css freetext field

### ISSUE THREAD

**Issue by omtr** [SiimKirjanen/seatreg#118]
it would be great if there was a freetext field in the seatreg settings where you can put in additional CSS for the look & feel, e.g. seat numbering, seat styling and more. i know that there is a legend function in the settings already, but some important parts of the styling are hardcoded into the code. having a custom CSS field would give users more flexibility and release the pressure from the dev to take care of the styling.

**Comment by omtr** [comment]
maybe something like this?
https://github.com/Cerdic/CSSTidy

**Comment by SiimKirjanen** [comment]
Maybe its best to use some plugin for it. https://wordpress.org/plugins/wp-add-custom-css/

**Comment by omtr** [comment]
but that plugin only adds custom css to posts, pages or custom post types. But SeatReg uses an Iframe where that custom css cannot be applied.
it would also be totally sufficient to have a distinct custom.css file somewhere within your plugin's file structure where picky guys luke me can add their own eye candy ;-)

**Comment by SiimKirjanen** [comment]
But the changes to this custom.css file will be lost next time you update the plugin.

**Comment by omtr** [comment]
not if you test for a custom.css file and ignore it if it's not existing ;-)

**Comment by omtr** [comment]
not if you test for a custom.css file and ignore it if it's not existing ;-)

**Comment by SiimKirjanen** [comment]
Oh okay so each time the plugin is updated you will copy paste the css file to plugin directory?

**Comment by omtr** [comment]
well, if you do not put it into your source code structure and let the users decide on their own if they want to place a custom.css file into wp-content/plugins/seatreg/css/, i assume it will not get overwritten during an update, right?

**Comment by SiimKirjanen** [comment]
I tested with one of the plugins I have that wanted update. I created custom file in plugin root directory and updated the plugin. After update the file was gone.

**Comment by omtr** [comment]
oh snap, i did not expect that :(

**Comment by SiimKirjanen** [comment]
Added this feature to master branch. Plugin update is scheduled to next week.

**Comment by SiimKirjanen** [comment]
Feature was added with version 1.36.0

**Comment by elisherer** [comment]
@SiimKirjanen Awesome feature, started using it right away
I wanted to make translation to some of the texts using `:before` elements but the text embedded is escaping `'` and `"` so I can't write something like:

```css
#room-nav-info-inner > .info-item:nth-child(2) > span:nth-of-type(2):before {
    position: absolute;
    content: "waiting approval";
    color: black;
}

#room-nav-info-inner > .info-item:nth-child(3) > span:nth-of-type(2):before {
    position: absolute;
    content: "occupied";
    color: black;
}

#room-nav-info-inner > .info-item > span:nth-of-type(2) {
    color: white;
}
```
(actual texts are just to demonstrate)
